version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - bumpp
  - bunx
  - direnv
  - elysia
  - insel
  - kwaa
  - lemmih
  - mitata
  - moeru
  - nixpkgs
  - pkgs
  - sonarjs
ignoreWords: []
import: []
